name: CD

on:
  push:
    branches:
      - dev
      - testing-pipeline
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Trigger Deployment Webhook
      run: |
        curl -X POST ${{ vars.WEBHOOK_URL }} -H "X-Custom-Secret: ${{ secrets.WEBHOOK_TOKEN }}"
